sudo: required
services:
  - docker

before_install:
  - docker build -t petorian/react-test -f ./client/Dockerfile.dev ./client


script:
  - docker run -e CI=true petorian/react-test npm test -- --coverage

after_success:
  - docker build -t petorian/multi-client ./client
  - docker build -t petorian/multi-nginx ./nginx
  - docker build -t petorian/multi-server ./server
  - docker build -t petorian/multi-worker ./worker



deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-086388529723"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"