sudo: required
services:
  - docker

before_install:
  - docker build -t petorian/react-test -f ./client/Dockerfile.dev ./client


script:
  - docker run -e CI=true petorian/react-test npm test -- --coverage

after_success:
  - docker build -t petorian/multi-client ./client
  - docker build -t petorian/multi-nginx ./nginx
  - docker build -t petorian/multi-server ./server
  - docker build -t petorian/multi-worker ./worker
  #login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #push images to docker hub
  - docker push petorian/multi-client
  - docker push petorian/multi-nginx 
  - docker push petorian/multi-server
  - docker push petorian/multi-worker


deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'multidocker-environment'
  bucket_name: 'elasticbeanstalk-us-east-1-086388529723'
  bucket_path: 'docker-multi'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
